name: Build Plugin ZIP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Sets up PHP with the required extensions and Composer
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: grpc, gmp
        tools: composer

    # 3. Installs all the dependencies from composer.json, creating the vendor folder
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    # 4. Creates a ZIP file containing all the necessary plugin files
    - name: Create Plugin ZIP
      run: zip -r aura-sync-plugin.zip . -x ".git/*" -x ".github/*"

    # 5. Uploads the created ZIP file so you can download it
    - name: Upload Plugin ZIP as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aura-sync-plugin
        path: aura-sync-plugin.zip
